# Generated by Django 4.1.4 on 2022-12-29 09:49

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tribes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(default='../placeholder_profile_xnpcwj.webp', max_length=255, verbose_name='image')),
                ('is_admin', models.BooleanField(default=False)),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tribes.tribe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
