# Generated by Django 4.1.4 on 2022-12-29 09:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tribes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.CharField(choices=[('NON', 'None'), ('WEK', 'Weekly'), ('TWK', 'Two weekly'), ('MON', 'Monthly'), ('YEA', 'Yearly')], default='NON', max_length=3)),
                ('subject', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('NON', 'None'), ('EDU', 'Education'), ('MED', 'Medical'), ('MUS', 'Music'), ('SHO', 'Shopping'), ('SPO', 'Sport'), ('VAC', 'Vacation'), ('WOR', 'Work')], default='NON', max_length=3)),
                ('accepted', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, size=None)),
                ('to', models.ManyToManyField(related_name='event', to=settings.AUTH_USER_MODEL)),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribes.tribe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
