# Generated by Django 4.1.4 on 2023-01-03 09:55

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='repeat',
            new_name='recurrence_type',
        ),
        migrations.AddField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(default=None),
        ),
    ]
