# Generated by Django 4.1.4 on 2023-01-03 11:24

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_recurrences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, default=None, null=True),
        ),
    ]
