# Generated by Django 4.1.4 on 2023-01-03 12:01

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_recurrences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(default=None),
            preserve_default=False,
        ),
    ]
