# Generated by Django 4.1.4 on 2023-01-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_recurrences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurrences',
        ),
    ]
