# Generated by Django 4.1.4 on 2023-01-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('NON', 'None'), ('REC', 'Is Recurrence'), ('WEK', 'Weekly'), ('TWK', 'Two weekly'), ('MON', 'Monthly'), ('YEA', 'Yearly')], default='NON', max_length=3),
        ),
    ]
