# Generated by Django 4.1.4 on 2023-01-04 15:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_recurrence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
