# Generated by Django 4.1.4 on 2023-01-05 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_alter_event_recurrence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accepted',
        ),
        migrations.AddField(
            model_name='event',
            name='accepted',
            field=models.ManyToManyField(related_name='event_accepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
