# Generated by Django 4.1.4 on 2023-01-06 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_remove_event_accepted_event_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('NON', 'None'), ('CLU', 'Club'), ('EDU', 'Education'), ('MED', 'Medical'), ('MUS', 'Music'), ('SHO', 'Shopping'), ('SPO', 'Sport'), ('VAC', 'Vacation'), ('WOR', 'Work')], default='NON', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='to',
            field=models.ManyToManyField(blank=True, null=True, related_name='event', to=settings.AUTH_USER_MODEL),
        ),
    ]
