# Generated by Django 4.1.4 on 2023-01-07 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_alter_event_category_alter_event_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='to',
            field=models.ManyToManyField(blank=True, related_name='event', to=settings.AUTH_USER_MODEL),
        ),
    ]
