# Generated by Django 4.1.4 on 2023-01-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('NON', 'None'), ('CLU', 'Club'), ('EDU', 'Education'), ('MED', 'Medical'), ('MUS', 'Music'), ('OTH', 'Other'), ('SHO', 'Shopping'), ('SPO', 'Sport'), ('VAC', 'Vacation'), ('WOR', 'Work')], default='NON', max_length=3),
        ),
    ]
