# Generated by Django 4.1.4 on 2023-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
