# Generated by Django 4.1.4 on 2023-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('NON', 'None'), ('CEL', 'Celebration'), ('CLU', 'Club'), ('EDU', 'Education'), ('MED', 'Medical'), ('MUS', 'Music'), ('OTH', 'Other'), ('OUT', 'Outing'), ('PET', 'Pets'), ('SHO', 'Shopping'), ('SPO', 'Sport'), ('VAC', 'Vacation'), ('WOR', 'Work')], default='NON', max_length=3),
        ),
    ]
