# Generated by Django 4.1.4 on 2022-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
