# Generated by Django 4.1.4 on 2022-12-29 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('NON', 'None'), ('ERM', 'Event reminder'), ('INV', 'Invitation')], default='NON', max_length=3)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
