# Generated by Django 4.1.4 on 2023-01-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
