# Generated by Django 4.1.4 on 2023-01-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='to_user',
            new_name='user',
        ),
    ]
